export const COLORS = {
  background: '#FAFAF8',
  surface: '#FFFFFF',
  primary: '#7B9E87',
  primarySoft: '#EDF4F0',
  primaryDim: '#C8D8CC',
  primaryDeep: '#5A7E68',
  ai: '#7C5BB7',
  aiBg: '#F3EDFA',
  aiBorder: '#E8E0F2',
  partner: '#E58B8B',
  partnerBorder: '#E8D5D5',
  error: '#E57373',
  text: '#2D2D2D',
  textBody: '#444',
  textSubtle: '#555',
  textMuted: '#888',
  textWeak: '#AAA',
  placeholder: '#BBB',
  disabled: '#CCC',
  border: '#E0E0E0',
  borderSoft: '#F0F0F0',
} as const;
